--CRUCE INICIAL RETENCIONES-CRM -- AJUSTAR
WITH

RETENCIONES AS(
SELECT DISTINCT RIGHT(CONCAT('0000000000',Contrato) ,10) AS Contrato
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE Contrato IS NOT NULL
GROUP BY Contrato),

CRM AS(
SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS ACT_ACCT_CD
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
WHERE ACT_ACCT_CD IS NOT NULL
GROUP BY ACT_ACCT_CD),

CRUCE AS(
SELECT DISTINCT r.Contrato 
FROM RETENCIONES r INNER JOIN CRM c ON r.Contrato=c.ACT_ACCT_CD
GROUP BY r.Contrato
)

SELECT COUNT(DISTINCT Contrato)
FROM CRUCE
