SELECT ESTRATEGIA_APLICADA, COUNT(DISTINCT Contrato) AS RegEstratRetenidos
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE AGRUPACION_SUBAREA="OFERTA"
AND SOLUCION_FINAL="RETENIDO"
GROUP BY ESTRATEGIA_APLICADA ORDER BY RegEstratRetenidos DESC
