WITH 

RETENIDOS AS(
SELECT DISTINCT RIGHT(CONCAT('0000000000',Contrato) ,10) AS Contrato, MAX(DATE(FECHA_FINALIZACION)) AS FechaTiquete, SOLUCION_FINAL
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE Contrato IS NOT NULL AND SOLUCION_FINAL="RETENIDO" 
--AND EXTRACT(YEAR FROM DATE(FECHA_FINALIZACION))=2021
GROUP BY Contrato, SOLUCION_FINAL)

SELECT COUNT(Contrato), EXTRACT(MONTH FROM FechaTiquete) AS Mes
FROM RETENIDOS
WHERE EXTRACT(YEAR FROM FechaTiquete)=2021
GROUP BY Mes ORDER BY Mes
