WITH 

BASE AS(
SELECT DISTINCT Contrato, FECHA_FINALIZACION AS FechaTiquete
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE Contrato IS NOT NULL AND SOLUCION_FINAL="RETENIDO" 
AND ESTRATEGIA_APLICADA<>"VISITA TECNICA" AND ESTRATEGIA_APLICADA<>"NO SE LE APLICO ESTRATEGIA"AND ESTRATEGIA_APLICADA<>"CAMBIO DE NOMBRE"
AND ESTRATEGIA_APLICADA<>"DISCULPAS POR EL INCONVENIENTE"AND ESTRATEGIA_APLICADA<>"SALIDA DEL PAIS POR 3 MESES"
AND ESTRATEGIA_APLICADA<>"SALIDA DEL PAIS POR 6 MESES"AND ESTRATEGIA_APLICADA<> "COORDINACION VISITA"AND ESTRATEGIA_APLICADA<>"RECONEXION SIN COSTO"
AND ESTRATEGIA_APLICADA<>"ANULACION FACTURA"AND ESTRATEGIA_APLICADA<>"SUSPENSION TEMPORAL"AND ESTRATEGIA_APLICADA<>"COVID19 X 3 MESES"
GROUP BY Contrato, FECHA_FINALIZACION),

REITERADOS AS(
SELECT DISTINCT r.Contrato AS ContratosR, FechaTiquete,FECHA_FINALIZACION AS FechaReiterado
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` r
RIGHT JOIN BASE b ON b.Contrato=r.Contrato
WHERE r.Contrato IS NOT NULL AND SOLUCION_FINAL="RETENIDO" 
AND ESTRATEGIA_APLICADA<>"VISITA TECNICA" AND ESTRATEGIA_APLICADA<>"NO SE LE APLICO ESTRATEGIA"AND ESTRATEGIA_APLICADA<>"CAMBIO DE NOMBRE"
AND ESTRATEGIA_APLICADA<>"DISCULPAS POR EL INCONVENIENTE"AND ESTRATEGIA_APLICADA<>"SALIDA DEL PAIS POR 3 MESES"
AND ESTRATEGIA_APLICADA<>"SALIDA DEL PAIS POR 6 MESES"AND ESTRATEGIA_APLICADA<> "COORDINACION VISITA"AND ESTRATEGIA_APLICADA<>"RECONEXION SIN COSTO"
AND ESTRATEGIA_APLICADA<>"ANULACION FACTURA"AND ESTRATEGIA_APLICADA<>"SUSPENSION TEMPORAL"AND ESTRATEGIA_APLICADA<>"COVID19 X 3 MESES"
AND DATE_DIFF(FECHA_FINALIZACION, FechaTiquete, DAY)>=30 AND DATE_DIFF(FECHA_FINALIZACION, FechaTiquete, DAY)<=90
GROUP BY r.Contrato, r.FECHA_FINALIZACION, FechaTiquete
)

SELECT EXTRACT(MONTH FROM FechaTiquete) as Mes, COUNT(DISTINCT ContratosR) as Reg 
FROM REITERADOS
GROUP BY Mes ORDER BY Mes
