WITH 

BASE AS(
SELECT DISTINCT Contrato, MAX(FECHA_FINALIZACION) AS FechaTiquete, SOLUCION_FINAL
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE Contrato IS NOT NULL
GROUP BY Contrato, SOLUCION_FINAL),

RETENIDOS_FLAG AS(
SELECT DISTINCT Contrato, FechaTiquete,SOLUCION_FINAL,
CASE WHEN SOLUCION_FINAL="RETENIDO" THEN COUNT(DISTINCT Contrato) END AS Retenidos,
CASE WHEN SOLUCION_FINAL="NO RETENIDO" THEN COUNT(DISTINCT Contrato) END AS NoRetenidos 
FROM BASE
GROUP BY Contrato, FechaTiquete, SOLUCION_FINAL
)

SELECT EXTRACT(MONTH FROM r.FechaTiquete) as Mes, COUNT(DISTINCT r.Contrato) AS Registros,
 COUNT(Retenidos) AS Retenidos, COUNT(Retenidos)/COUNT(DISTINCT r.Contrato) AS PorcRet,
 COUNT(NoRetenidos) as NoRetenidos, COUNT(NoRetenidos)/COUNT(DISTINCT r.Contrato) AS PorcNoRet
FROM RETENIDOS_FLAG r
GROUP BY Mes ORDER BY Mes

