WITH 

BASE AS(
SELECT DISTINCT Contrato, MAX(FECHA_FINALIZACION) AS FechaTiquete, SOLUCION_FINAL, ANTIGUEDAD
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE Contrato IS NOT NULL
GROUP BY Contrato, SOLUCION_FINAL,ANTIGUEDAD),

RETENIDOS_FLAG AS(
SELECT DISTINCT Contrato, FechaTiquete,SOLUCION_FINAL,ANTIGUEDAD,
CASE WHEN SOLUCION_FINAL="RETENIDO" THEN COUNT(DISTINCT Contrato) END AS Retenidos,
CASE WHEN SOLUCION_FINAL="NO RETENIDO" THEN COUNT(DISTINCT Contrato) END AS NoRetenidos 
FROM BASE
GROUP BY Contrato, FechaTiquete, SOLUCION_FINAL, ANTIGUEDAD
),

TENURE AS (
SELECT DISTINCT Contrato, ANTIGUEDAD,FechaTiquete,Retenidos,NoRetenidos,
CASE WHEN ANTIGUEDAD="MENOS DE UN AÑO" THEN "<1 A"
 WHEN ANTIGUEDAD="1 a 3 AÑOS" THEN "1-3 A"
 WHEN ANTIGUEDAD="DE 3 a 6 AÑOS" THEN "3-6 A"
 WHEN ANTIGUEDAD="DE 6 a 10 AÑOS" THEN "6-10 A"
 WHEN ANTIGUEDAD="MAS DE 10 AÑOS" THEN ">10 A" END AS TENURE
FROM RETENIDOS_FLAG
GROUP BY Contrato, ANTIGUEDAD,FechaTiquete,Retenidos,NoRetenidos
)

SELECT EXTRACT(MONTH FROM r.FechaTiquete) as Mes, Tenure, COUNT(DISTINCT r.Contrato) AS Registros,
 COUNT(Retenidos) AS Retenidos, COUNT(Retenidos)/COUNT(DISTINCT r.Contrato) AS PorcRet,
 COUNT(NoRetenidos) as NoRetenidos, COUNT(NoRetenidos)/COUNT(DISTINCT r.Contrato) AS PorcNoRet
FROM TENURE r
GROUP BY Mes, Tenure ORDER BY Mes, CASE WHEN Tenure="<1 A" THEN 1
 WHEN Tenure="1-3 A" THEN 2
 WHEN Tenure= "3-6 A" THEN 3
 WHEN Tenure="6-10 A" THEN 4
 WHEN Tenure=">10 A" THEN 5 END
