WITH 

RETENIDOS AS(
SELECT DISTINCT RIGHT(CONCAT('0000000000',Contrato) ,10) AS Contrato, MAX(DATE(FECHA_FINALIZACION)) AS FechaTiquete, SOLUCION_FINAL
FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_TIQUETES_GENERALES_DE_DESCONEXIONES_T` 
WHERE Contrato IS NOT NULL AND SOLUCION_FINAL="RETENIDO" 
AND EXTRACT(YEAR FROM DATE(FECHA_FINALIZACION))=2021
GROUP BY Contrato, SOLUCION_FINAL
),

CHURNERSCRM AS(
    SELECT DISTINCT RIGHT(CONCAT('0000000000',ACT_ACCT_CD) ,10) AS ACT_ACCT_CD, MAX(CST_CHRN_DT) AS Maxfecha
    FROM `gcp-bia-tmps-vtr-dev-01.gcp_temp_cr_dev_01.2022-02-02_CRM_BULK_FILE_FINAL_HISTORIC_DATA_2021_D`
    WHERE EXTRACT(YEAR FROM CST_CHRN_DT)=2021
    GROUP BY ACT_ACCT_CD
    HAVING EXTRACT (MONTH FROM Maxfecha) = EXTRACT (MONTH FROM MAX(FECHA_EXTRACCION))
)

SELECT 
COUNT(DISTINCT r.Contrato)
FROM RETENIDOS r INNER JOIN CHURNERSCRM  c ON c.ACT_ACCT_CD=r.Contrato
WHERE MaxFecha>FechaTiquete 
AND EXTRACT(MONTH FROM FechaTiquete)=12
AND EXTRACT(MONTH FROM MaxFecha)=12
